.\" Manpage for yap++.
.\" Contact idealtitude@gmail.com to correct errors or typos.
.TH man 8 "07 May 2022" "1.0" "yap++ man page"
.SH NAME
yap++ \- transpile a yap file to a html document
.SH SYNOPSIS
yap [OPTIONS]... [FILES]...
.SH DESCRIPTION
yap++ is the C++ version of yap, an html preprocessor written in Python.
.SH OPTIONS
The yap++ executable takes the following option
.SH SEE ALSO
yap(1)
.SH BUGS
No known bugs.
.SH AUTHOR
idealtitude (idealtitude@gmail.com)
